### PR TITLE
Use TypeID enum in both C and C++

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by abinashmeher999** [comment]
Ah, this works for both. I couldn't think of that. Thanks a lot! :smile:

**Comment by abinashmeher999** [comment]
Should we wait for the tests. The other branch will be tested anyways.

**Comment by abinashmeher999** [comment]
It passed for only a few.

**Comment by isuruf** [comment]
Tests will fail, because you haven't included the new file in  symengine/CMakeLists.txt

**Comment by abinashmeher999** [comment]
Ah, I missed that. I will correct it. Thanks!

**Comment by isuruf** [comment]
cc @certik

**Comment by certik** [comment]
This looks great to me.

**Pull request merged**
